ORE_SKILL_MAP = {
    # Simple Ore Processing
    "Veldspar": "Simple Ore Processing",
    "Veldspar II-Grade": "Simple Ore Processing",
    "Veldspar III-Grade": "Simple Ore Processing",
    "Veldspar IV-Grade": "Simple Ore Processing",
    "Scordite": "Simple Ore Processing",
    "Scordite II-Grade": "Simple Ore Processing",
    "Scordite III-Grade": "Simple Ore Processing",
    "Scordite IV-Grade": "Simple Ore Processing",
    "Pyroxeres": "Simple Ore Processing",
    "Pyroxeres II-Grade": "Simple Ore Processing",
    "Pyroxeres III-Grade": "Simple Ore Processing",
    "Pyroxeres IV-Grade": "Simple Ore Processing",
    "Plagioclase": "Simple Ore Processing",
    "Plagioclase II-Grade": "Simple Ore Processing",
    "Plagioclase III-Grade": "Simple Ore Processing",
    "Plagioclase IV-Grade": "Simple Ore Processing",
    "Azure Plagioclase": "Simple Ore Processing",
    "Rich Plagioclase": "Simple Ore Processing",
    "Solid Pyroxeres": "Simple Ore Processing",
    "Viscous Pyroxeres": "Simple Ore Processing",
    "Condensed Scordite": "Simple Ore Processing",
    "Massive Scordite": "Simple Ore Processing",
    "Stable Veldspar": "Simple Ore Processing",
    "Concentrated Veldspar": "Simple Ore Processing",
    "Dense Veldspar": "Simple Ore Processing",

    # Coherent Ore Processing
    "Omber": "Coherent Ore Processing",
    "Omber II-Grade": "Coherent Ore Processing",
    "Omber III-Grade": "Coherent Ore Processing",
    "Omber IV-Grade": "Coherent Ore Processing",
    "Kernite": "Coherent Ore Processing",
    "Kernite II-Grade": "Coherent Ore Processing",
    "Kernite III-Grade": "Coherent Ore Processing",
    "Kernite IV-Grade": "Coherent Ore Processing",
    "Jaspet": "Coherent Ore Processing",
    "Jaspet II-Grade": "Coherent Ore Processing",
    "Jaspet III-Grade": "Coherent Ore Processing",
    "Jaspet IV-Grade": "Coherent Ore Processing",
    "Hemorphite": "Coherent Ore Processing",
    "Hemorphite II-Grade": "Coherent Ore Processing",
    "Hemorphite III-Grade": "Coherent Ore Processing",
    "Hemorphite IV-Grade": "Coherent Ore Processing",
    "Hedbergite": "Coherent Ore Processing",
    "Hedbergite II-Grade": "Coherent Ore Processing",
    "Hedbergite III-Grade": "Coherent Ore Processing",
    "Hedbergite IV-Grade": "Coherent Ore Processing",
    "Silvery Omber": "Coherent Ore Processing",
    "Golden Omber": "Coherent Ore Processing",
    "Platinoid Omber": "Coherent Ore Processing",
    "Luminous Kernite": "Coherent Ore Processing",
    "Fiery Kernite": "Coherent Ore Processing",
    "Pristine Jaspet": "Coherent Ore Processing",
    "Pure Jaspet": "Coherent Ore Processing",
    "Glazed Hedbergite": "Coherent Ore Processing",
    "Vitric Hedbergite": "Coherent Ore Processing",
    "Lustrous Hedbergite": "Coherent Ore Processing",
    "Radiant Hemorphite": "Coherent Ore Processing",
    "Vivid Hemorphite": "Coherent Ore Processing",

    # Variegated Ore Processing
    "Arkonor": "Variegated Ore Processing",
    "Arkonor II-Grade": "Variegated Ore Processing",
    "Arkonor III-Grade": "Variegated Ore Processing",
    "Arkonor IV-Grade": "Variegated Ore Processing",
    "Bistot": "Variegated Ore Processing",
    "Bistot II-Grade": "Variegated Ore Processing",
    "Bistot III-Grade": "Variegated Ore Processing",
    "Bistot IV-Grade": "Variegated Ore Processing",
    "Crokite": "Variegated Ore Processing",
    "Crokite II-Grade": "Variegated Ore Processing",
    "Crokite III-Grade": "Variegated Ore Processing",
    "Crokite IV-Grade": "Variegated Ore Processing",
    "Spodumain": "Variegated Ore Processing",
    "Spodumain II-Grade": "Variegated Ore Processing",
    "Spodumain III-Grade": "Variegated Ore Processing",
    "Spodumain IV-Grade": "Variegated Ore Processing",
    "Crimson Arkonor": "Variegated Ore Processing",
    "Prime Arkonor": "Variegated Ore Processing",
    "Flawless Arkonor": "Variegated Ore Processing",
    "Triclinic Bistot": "Variegated Ore Processing",
    "Monoclinic Bistot": "Variegated Ore Processing",
    "Cubic Bistot": "Variegated Ore Processing",
    "Sharp Crokite": "Variegated Ore Processing",
    "Crystalline Crokite": "Variegated Ore Processing",
    "Pellucid Crokite": "Variegated Ore Processing",
    "Bright Spodumain": "Variegated Ore Processing",
    "Gleaming Spodumain": "Variegated Ore Processing",
    "Dazzling Spodumain": "Variegated Ore Processing",

    # Complex Ore Processing
    "Ochre": "Complex Ore Processing",
    "Ochre II-Grade": "Complex Ore Processing",
    "Ochre III-Grade": "Complex Ore Processing",
    "Ochre IV-Grade": "Complex Ore Processing",
    "Onyx Ochre": "Complex Ore Processing",
    "Obsidian Ochre": "Complex Ore Processing",
    "Jet Ochre": "Complex Ore Processing",
    "Dark Ochre": "Complex Ore Processing",
    "Dark Ochre II-Grade": "Complex Ore Processing",
    "Dark Ochre III-Grade": "Complex Ore Processing",
    "Dark Ochre IV-Grade": "Complex Ore Processing",
    "Gneiss": "Complex Ore Processing",
    "Gneiss II-Grade": "Complex Ore Processing",
    "Gneiss III-Grade": "Complex Ore Processing",
    "Gneiss IV-Grade": "Complex Ore Processing",
    "Iridescent Gneiss": "Complex Ore Processing",
    "Prismatic Gneiss": "Complex Ore Processing",
    "Brilliant Gneiss": "Complex Ore Processing",

    # Common Moon Ore Processing
    "Cobaltite": "Common Moon Ore Processing",
    "Euxenite": "Common Moon Ore Processing",
    "Titanite": "Common Moon Ore Processing",
    "Chromite": "Common Moon Ore Processing",
    "Copious Cobaltite": "Common Moon Ore Processing",
    "Twinkling Cobaltite": "Common Moon Ore Processing",
    "Copious Euxenite": "Common Moon Ore Processing",
    "Twinkling Euxenite": "Common Moon Ore Processing",
    "Copious Titanite": "Common Moon Ore Processing",
    "Twinkling Titanite": "Common Moon Ore Processing",
    "Lavish Chromite": "Common Moon Ore Processing",
    "Shimmering Chromite": "Common Moon Ore Processing",

    # Rare Moon Ore Processing
    "Otavite": "Rare Moon Ore Processing",
    "Sperrylite": "Rare Moon Ore Processing",
    "Vanadinite": "Rare Moon Ore Processing",
    "Yttrium": "Rare Moon Ore Processing",
    "Lavish Otavite": "Rare Moon Ore Processing",
    "Shimmering Otavite": "Rare Moon Ore Processing",
    "Lavish Sperrylite": "Rare Moon Ore Processing",
    "Shimmering Sperrylite": "Rare Moon Ore Processing",
    "Lavish Vanadinite": "Rare Moon Ore Processing",
    "Shimmering Vanadinite": "Rare Moon Ore Processing",

    # Exceptional Moon Ore Processing
    "Loparite": "Exceptional Moon Ore Processing",
    "Pollucite": "Exceptional Moon Ore Processing",
    "Monazite": "Exceptional Moon Ore Processing",
    "Xenotime": "Exceptional Moon Ore Processing",
    "Zircon": "Exceptional Moon Ore Processing",
    "Cinnabar": "Exceptional Moon Ore Processing",
    "Ytterbite": "Exceptional Moon Ore Processing",
    "Replete Zircon": "Exceptional Moon Ore Processing",
    "Glowing Zircon": "Exceptional Moon Ore Processing",
    "Replete Pollucite": "Exceptional Moon Ore Processing",
    "Glowing Pollucite": "Exceptional Moon Ore Processing",
    "Replete Cinnabar": "Exceptional Moon Ore Processing",
    "Glowing Cinnabar": "Exceptional Moon Ore Processing",
    "Bountiful Xenotime": "Exceptional Moon Ore Processing",
    "Shining Xenotime": "Exceptional Moon Ore Processing",
    "Bountiful Monazite": "Exceptional Moon Ore Processing",
    "Shining Monazite": "Exceptional Moon Ore Processing",
    "Bountiful Loparite": "Exceptional Moon Ore Processing",
    "Shining Loparite": "Exceptional Moon Ore Processing",
    "Bountiful Ytterbite": "Exceptional Moon Ore Processing",
    "Shining Ytterbite": "Exceptional Moon Ore Processing",

    # High-Quality Asteroid Ores
    "Scintillating Hemorphite": "Coherent Ore Processing",
    "Immaculate Jaspet": "Coherent Ore Processing",
    "Resplendant Kernite": "Coherent Ore Processing",
    "Sparkling Plagioclase": "Simple Ore Processing",
    "Opulent Pyroxeres": "Simple Ore Processing",
    "Glossy Scordite": "Simple Ore Processing",

    # Ubiquitous Moon Ore Processing
    "Bitumens": "Ubiquitous Moon Ore Processing",
    "Coesite": "Ubiquitous Moon Ore Processing",
    "Sylvite": "Ubiquitous Moon Ore Processing",
    "Zeolites": "Ubiquitous Moon Ore Processing",
    "Scheelite": "Ubiquitous Moon Ore Processing",
    "Carnotite": "Ubiquitous Moon Ore Processing",
    "Brimful Zeolites": "Ubiquitous Moon Ore Processing",
    "Glistening Zeolites": "Ubiquitous Moon Ore Processing",
    "Brimful Sylvite": "Ubiquitous Moon Ore Processing",
    "Glistening Sylvite": "Ubiquitous Moon Ore Processing",
    "Brimful Bitumens": "Ubiquitous Moon Ore Processing",
    "Glistening Bitumens": "Ubiquitous Moon Ore Processing",
    "Brimful Coesite": "Ubiquitous Moon Ore Processing",
    "Glistening Coesite": "Ubiquitous Moon Ore Processing",
    "Copious Scheelite": "Ubiquitous Moon Ore Processing",
    "Twinkling Scheelite": "Ubiquitous Moon Ore Processing",
    "Replete Carnotite": "Ubiquitous Moon Ore Processing",
    "Glowing Carnotite": "Ubiquitous Moon Ore Processing",

    # Ice Processing
    "Faded Volatile Ice": "Ice Processing",
    "Fresh Volatile Ice": "Ice Processing",
    "Friable Volatile Ice": "Ice Processing",
    "Pristine Volatile Ice": "Ice Processing",
    "Faded Stable Ice": "Ice Processing",
    "Fresh Stable Ice": "Ice Processing",
    "Friable Stable Ice": "Ice Processing",
    "Pristine Stable Ice": "Ice Processing",
    "Faded Dense Ice": "Ice Processing",
    "Fresh Dense Ice": "Ice Processing",
    "Friable Dense Ice": "Ice Processing",
    "Pristine Dense Ice": "Ice Processing",
    "Faded Crystalline Ice": "Ice Processing",
    "Fresh Crystalline Ice": "Ice Processing",
    "Friable Crystalline Ice": "Ice Processing",
    "Pristine Crystalline Ice": "Ice Processing",
    "Clear Icicle": "Ice Processing",
    "Clear Icicle IV-Grade": "Ice Processing",
    "Glacial Mass": "Ice Processing",
    "Glacial Mass IV-Grade": "Ice Processing",
    "Blue Ice": "Ice Processing",
    "Blue Ice IV-Grade": "Ice Processing",
    "White Glaze": "Ice Processing",
    "White Glaze IV-Grade": "Ice Processing",
    "Glare Crust": "Ice Processing",
    "Dark Glitter": "Ice Processing",
    "Gelidus": "Ice Processing",
    "Krystallos": "Ice Processing",
    "Thick Blue Ice": "Ice Processing",
    "Pristine White Glaze": "Ice Processing",
    "Smooth Glacial Mass": "Ice Processing",
    "Enriched Clear Icicle": "Ice Processing",
    "Azure Ice": "Ice Processing",
    "Crystalline Icicle": "Ice Processing",

    # Abyssal Ore Processing
    "Nephrite": "Abyssal Ore Processing",
    "Amethystic Crystallite": "Abyssal Ore Processing",
    "Talassonite": "Abyssal Ore Processing",
    "Rakovene": "Abyssal Ore Processing",
    "Bezdnacine": "Abyssal Ore Processing",
    "Abyssal Talassonite": "Abyssal Ore Processing",
    "Hadal Talassonite": "Abyssal Ore Processing",
    "Abyssal Bezdnacine": "Abyssal Ore Processing",
    "Hadal Bezdnacine": "Abyssal Ore Processing",
    "Abyssal Rakovene": "Abyssal Ore Processing",
    "Hadal Rakovene": "Abyssal Ore Processing",
    "Nesosilicate Rakovene": "Abyssal Ore Processing",
    "Banidine": "Abyssal Ore Processing",
    "Augumene": "Abyssal Ore Processing",
    "Mercium": "Abyssal Ore Processing",
    "Lyavite": "Abyssal Ore Processing",
    "Pithix": "Abyssal Ore Processing",
    "Green Arisite": "Abyssal Ore Processing",
    "Oeryl": "Abyssal Ore Processing",
    "Geodite": "Abyssal Ore Processing",
    "Polygypsum": "Abyssal Ore Processing",
    "Zuthrine": "Abyssal Ore Processing",

    # Mutanite Ore Processing
    "Amperum Mutanite": "Mutanite Ore Processing",
    "Peregrinus Mutanite": "Mutanite Ore Processing",
    "Conflagrati Mutanite": "Mutanite Ore Processing",
    "Solis Mutanite": "Mutanite Ore Processing",
    "Tenebraet Mutanite": "Mutanite Ore Processing",
    "Admixti Mutanite": "Mutanite Ore Processing",

    # Kylixium Ore Processing
    "Kylixium": "Kylixium Ore Processing",
    "Kylixium II-Grade": "Kylixium Ore Processing",
    "Kylixium III-Grade": "Kylixium Ore Processing",
    "Kylixium IV-Grade": "Kylixium Ore Processing",
    "Kaolin Kylixium": "Kylixium Ore Processing",
    "Argil Kylixium": "Kylixium Ore Processing",
    "Adobe Kylixium": "Kylixium Ore Processing",

    # Griemeer Ore Processing
    "Griemeer": "Griemeer Ore Processing",
    "Griemeer II-Grade": "Griemeer Ore Processing",
    "Griemeer III-Grade": "Griemeer Ore Processing",
    "Griemeer IV-Grade": "Griemeer Ore Processing",
    "Clear Griemeer": "Griemeer Ore Processing",
    "Inky Griemeer": "Griemeer Ore Processing",
    "Opaque Griemeer": "Griemeer Ore Processing",

    # Zarzakh Moon Ore Processing
    "Nocxite": "Zarzakh Moon Ore Processing",
    "Nocxite II-Grade": "Zarzakh Moon Ore Processing",
    "Nocxite III-Grade": "Zarzakh Moon Ore Processing",
    "Nocxite IV-Grade": "Zarzakh Moon Ore Processing",
    "Fragrant Nocxite": "Zarzakh Moon Ore Processing",
    "Intoxicating Nocxite": "Zarzakh Moon Ore Processing",
    "Ambrosial Nocxite": "Zarzakh Moon Ore Processing",
    "Hezorime": "Zarzakh Moon Ore Processing",
    "Hezorime II-Grade": "Zarzakh Moon Ore Processing",
    "Hezorime III-Grade": "Zarzakh Moon Ore Processing",
    "Hezorime IV-Grade": "Zarzakh Moon Ore Processing",
    "Dull Hezorime": "Zarzakh Moon Ore Processing",
    "Serrated Hezorime": "Zarzakh Moon Ore Processing",
    "Sharp Hezorime": "Zarzakh Moon Ore Processing",
    "Ueganite": "Zarzakh Moon Ore Processing",
    "Ueganite II-Grade": "Zarzakh Moon Ore Processing",
    "Ueganite III-Grade": "Zarzakh Moon Ore Processing",
    "Ueganite IV-Grade": "Zarzakh Moon Ore Processing",
    "Foggy Ueganite": "Zarzakh Moon Ore Processing",
    "Overcast Ueganite": "Zarzakh Moon Ore Processing",
    "Stormy Ueganite": "Zarzakh Moon Ore Processing",

    # Mercoxit
    "Mercoxit": "Mercoxit Ore Processing",
    "Mercoxit II-Grade": "Mercoxit Ore Processing",
    "Mercoxit III-Grade": "Mercoxit Ore Processing",
    "Magma Mercoxit": "Mercoxit Ore Processing",
    "Vitreous Mercoxit": "Mercoxit Ore Processing",

    # Mordunium
    "Mordunium": "Mordunium Ore Processing",
    "Mordunium II-Grade": "Mordunium Ore Processing",
    "Mordunium III-Grade": "Mordunium Ore Processing",
    "Plum Mordunium": "Mordunium Ore Processing",
    "Prize Mordunium": "Mordunium Ore Processing",
    "Plunder Mordunium": "Mordunium Ore Processing",

    # Ytirium
    "Ytirium": "Ytirium Ore Processing",
    "Ytrium II-Grade": "Ytirium Ore Processing",
    "Ytirium III-Grade": "Ytirium Ore Processing",
    "Bootleg Ytirium": "Ytirium Ore Processing",
    "Firewater Ytirium": "Ytirium Ore Processing",
    "Moonshine Ytirium": "Ytirium Ore Processing",

    # Eifyrium
    "Eifyrium": "Eifyrium Ore Processing",
    "Eifyrium II-Grade": "Eifyrium Ore Processing",
    "Eifyrium III-Grade": "Eifyrium Ore Processing",
    "Doped Eifyrium": "Eifyrium Ore Processing",
    "Boosted Eifyrium": "Eifyrium Ore Processing",
    "Augmented Eifyrium": "Eifyrium Ore Processing",

    # Ducinium
    "Ducinium": "Ducinium Ore Processing",
    "Ducinium II-Grade": "Ducinium Ore Processing",
    "Ducinium III-Grade": "Ducinium Ore Processing",
    "Noble Ducinium": "Ducinium Ore Processing",
    "Royal Ducinium": "Ducinium Ore Processing",
    "Imperial Ducinium": "Ducinium Ore Processing",

    # Tyranite
    "Tyranite": "Tyranite Ore Processing",
}

def get_processing_skill_for_ore(ore_name):
    # Try direct match
    skill = ORE_SKILL_MAP.get(ore_name)
    if skill:
        return skill
    # Try removing 'Compressed ' prefix
    if ore_name.startswith("Compressed "):
        base_ore = ore_name.replace("Compressed ", "")
        return ORE_SKILL_MAP.get(base_ore)
    # Try removing 'Batch Compressed ' prefix
    if ore_name.startswith("Batch Compressed "):
        base_ore = ore_name.replace("Batch Compressed ", "")
        return ORE_SKILL_MAP.get(base_ore)
    return None